if("${PROJECT_SOURCE_DIR}" STREQUAL "${CMAKE_SOURCE_DIR}")
    set(TGT_PREFIX)
    set(OPT_PREFIX)
else()
    set(TGT_PREFIX "${PROJECT_NAME}_")
    string(TOUPPER "${TGT_PREFIX}" OPT_PREFIX)
endif()

macro(config_option OPT_NAME OPT_TYPE OPT_DESC)
    if(${ARGC} GREATER 3)
        set(_OPT_DEFAULT ${ARGN})
    else()
        set(_OPT_DEFAULT)
    endif()
    if("${OPT_TYPE}" STREQUAL "BOOL")
        option("${OPT_PREFIX}${OPT_NAME}" "${OPT_DESC}" ${_OPT_DEFAULT})
    else()
        set("${OPT_PREFIX}${OPT_NAME}" ${_OPT_DEFAULT} CACHE "${OPT_TYPE}" "${OPT_DESC}")
    endif()
    if(NOT "${OPT_PREFIX}" STREQUAL "")
        set("${OPT_NAME}" ${${OPT_PREFIX}${OPT_NAME}})
    endif()
    set("_${OPT_PREFIX}${OPT_NAME}_DEFAULT" ${OPT_DEFAULT})
    set("_${OPT_PREFIX}${OPT_NAME}_TYPE" "${OPT_TYPE}")
    set("_${OPT_PREFIX}${OPT_NAME}_DESC" "${OPT_DESC}")
endmacro()

macro(override_config_option OPT_NAME)
    set("${OPT_PREFIX}${OPT_NAME}" ${ARGN} CACHE "${_${OPT_PREFIX}${OPT_NAME}_TYPE}" "${_${OPT_PREFIX}${OPT_NAME}_DESC}" FORCE)
endmacro()
